# Generated by Django 4.0.6 on 2022-07-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название комикса')),
                ('title_src', models.CharField(max_length=255, unique=True, verbose_name='Ссылка на комикс')),
                ('img_src', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на изображение')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('added_title', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'комикс',
                'verbose_name_plural': 'Комиксы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер главы')),
                ('pages', models.TextField(verbose_name='Список спрайтов')),
                ('added_chapter', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('title_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.title', verbose_name='Название комикса')),
            ],
            options={
                'verbose_name': 'главу',
                'verbose_name_plural': 'Главы',
                'ordering': ['number'],
            },
        ),
    ]
